const GET_ALL_POSTS = 'GET_ALL_POSTS';
const GET_SINGLE_POST = 'GET_SINGLE_POST';
const GET_USER_ADMIN = "GET_USER_ADMIN";
const GET_SINGLE_USER = 'GET_SINGLE_USER';
const POST_USER = 'POST_USER'
const SEARCH_BY_TITLE = 'SEARCH_BY_TITLE';
const CATEGORY_POST = "CATEGORY_POST";
const CATEGORY_SPECEALTY = "CATEGORY_SPECEALTY"
const GET_FILTER_TYPE = 'GET_FILTER_TYPE';




module.exports = {
    GET_ALL_POSTS,
    GET_SINGLE_POST,
    GET_USER_ADMIN,
    GET_SINGLE_USER,
    SEARCH_BY_TITLE,
    POST_USER,
    CATEGORY_POST,
    CATEGORY_SPECEALTY,
    GET_FILTER_TYPE,
}