const GET_ALL_POSTS = 'GET_ALL_POSTS';
const GET_SINGLE_POST = 'GET_SINGLE_POST';
const GET_USER_ADMIN = "GET_USER_ADMIN";
const GET_SINGLE_USER = 'GET_SINGLE_USER';
const POST_USER = 'POST_USER'
const SEARCH_BY_NAME = 'SEARCH_BY_NAME';


module.exports = {
    GET_ALL_POSTS,
    GET_SINGLE_POST,
    GET_USER_ADMIN,
    GET_SINGLE_USER,
    SEARCH_BY_NAME,
    POST_USER,
}