const GET_ALL_POSTS = 'GET_ALL_POSTS';
const GET_SINGLE_POST = 'GET_SINGLE_POST';
const GET_USER_ADMIN = "GET_USER_ADMIN";
const GET_SINGLE_USER = 'GET_SINGLE_USER'


module.exports = {
    GET_ALL_POSTS,
    GET_SINGLE_POST,
    GET_USER_ADMIN,
    GET_SINGLE_USER
}