const postsDB = [
  {
    user_id: "e2f1cfbd-6c29-477d-b4eb-dbb69081dfd1",
    typePost: "Offer",
    title: "Se ofrecen servicios de albañileria y relacionados",
    description: "Venenatis phasellus quis vel enim sociosqu congue quam.",
    image: "",
    priceRange: ["500", "1000"],
    timeRange: ["mañana", "tarde"],
    category_id: 101,
    specialty_id: 1000,
    paymentMethods: ["Efectivo", "MercadoPago", "Transferencia", "Crédito", "Débito"],
    workingArea: ["CABA", "GBA Zona Sur"],
    isActive: true,
  },
  {
    user_id: "c58ef3a8-1ad7-4ce4-ab20-5c36ad327f9b",
    typePost: "Offer",
    title: "Electricista a domicilio",
    description: "Venenatis phasellus quis vel enim sociosqu congue quam.",
    image: "",
    priceRange: ["800", "1000"],
    timeRange: ["mañana", "tarde"],
    category_id: 101,
    specialty_id: 1037,
    paymentMethods: ["Efectivo", "Mercado Pago"],
    workingArea: ["CABA", "GBA Zona Sur", "GBA Zona Norte"],
    isActive: true,
  },
  {
    user_id: "880fb38e-b686-49d7-8002-a3542d106d36",
    typePost: "Offer",
    title: "Cuidado de niños a domicilio / en hogar",
    description: "Venenatis phasellus quis vel enim sociosqu congue quam.",
    image: "",
    priceRange: ["500", "1000"],
    timeRange: ["mañana", "tarde", "noche"],
    category_id: 105,
    specialty_id: 5008,
    paymentMethods: ["Efectivo"],
    workingArea: ["CABA"],
    isActive: true,
  },
  {
    user_id: "e3275235-8ea1-42a4-968d-d98255f75435",
    typePost: "Offer",
    title: "Costurera: La mejor de Bernal",
    description: "Venenatis phasellus quis vel enim sociosqu congue quam.",
    image: "",
    priceRange: ["500", "1500"],
    timeRange: ["mañana", "tarde"],
    category_id: 101,
    specialty_id: 1028,
    paymentMethods: ["Efectivo", "Mercado Pago"],
    workingArea: ["CABA"],
    isActive: true,
  },
  {
    user_id: "befba476-a405-4b2d-b0b2-bbd7fa45fe5a",
    typePost: "Offer",
    title: "Carpintero: 50 años de experiencia",
    description: "Ultrices eleifend dis porttitor auctor condimentum vehicula habitasse, facilisis duis.",
    image: "",
    priceRange: ["700", "1500"],
    timeRange: ["mañana", "tarde"],
    category_id: 101,
    specialty_id: 1017,
    paymentMethods: ["Mercado Pago"],
    workingArea: ["CABA", "GBA Zona Norte"],
    isActive: true,
  },
  {
    user_id: "3210fa1e-9e2f-4b07-9ff7-3f58425ac564",
    typePost: "Petition",
    title: "Profesor de programación. Preparo alumnos para checkpoints de Henry",
    description: "sollicitudin magna euismod aenean quisque eu. Ullamcorper tempor habitasse sociis inceptos ultrices ornare integer.",
    image: "",
    priceRange: ["200", "800"],
    timeRange: ["mañana", "tarde"],
    category_id: 107,
    specialty_id: 7001,
    paymentMethods: ["Mercado Pago"],
    workingArea: ["CABA"],
    isActive: true,
  },
  {
    user_id: "c294a8ef-3bc1-4210-be26-615dc0d3c3b6",
    typePost: "Offer",
    title: "Zapatero Zona Sur",
    description: "habitasse sociis inceptos ultrices ornare integer, nostra a nunc ultricies gravida facilis integer.",
    image: "",
    priceRange: ["200", "1000"],
    timeRange: ["mañana", "tarde"],
    category_id: 101,
    specialty_id: 1115,
    paymentMethods: ["Mercado Pago"],
    workingArea: ["GBA Zona Sur"],
    isActive: false,
  },
  {
    user_id: "d99f4ab1-c88e-49d3-b912-62057cb4a227",
    typePost: "Petition",
    title: "Volantero para evento social",
    description: "habitasse sociis inceptos ultrices ornare integer, nostra a nunc ultricies gravida facilis integer.",
    image: "",
    priceRange: ["200", "800"],
    timeRange: ["mañana", "tarde"],
    category_id: 101,
    specialty_id: 1113,
    paymentMethods: ["Efectivo", "Mercado Pago"],
    workingArea: ["GBA Zona Norte", "CABA", "GBA Zona Sur"],
    isActive: false,
  },
  {
    user_id: "416541a4-7724-4fbb-a5ff-ea9f5b1b27bb",
    typePost: "Offer",
    title: "Gasista matriculado Precios imbatibles",
    description: "habitasse sociis inceptos ultrices ornare integer, nostra a nunc ultricies gravida facilis integer.",
    image: "",
    priceRange: ["500", "2500"],
    timeRange: ["mañana", "tarde"],
    category_id: 101,
    specialty_id: 1116,
    paymentMethods: ["Transferencia", "Efectivo", "Mercado Pago"],
    workingArea: ["GBA Zona Sur"],
    isActive: true,
  },
  {
    user_id: "e03a184d-7485-4708-9cc2-205c81f06e3e",
    typePost: "Offer",
    title: "Chofer a domicilio",
    description: "habitasse sociis inceptos ultrices ornare integer, nostra a nunc ultricies gravida facilis integer.",
    image: "",
    priceRange: ["200", "800"],
    timeRange: ["mañana", "tarde"],
    category_id: 103,
    specialty_id: 3001,
    paymentMethods: ["Mercado Pago"],
    workingArea: ["CABA"],
    isActive: false,
  },
];

module.exports = postsDB;
