const postsDB = [
  {
    typePost: "Offer",
    title: "Plomeria",
    description: "Venenatis phasellus quis vel enim sociosqu congue quam.",
    image: "",
    priceRange: ["500", "1000"],
    timeRange: ["mañana", "tarde"],
    category: "Plomería",
    specialty: "Plomero",
    paymentMethods: ["Mercado Pago"],
    workingArea: ["CABA", "GBA Zona Sur"],
    isActive: true,
  },
  {
    typePost: "Offer",
    title: "Electricista",
    description: "Venenatis phasellus quis vel enim sociosqu congue quam.",
    image: "",
    priceRange: ["800", "1000"],
    timeRange: ["mañana", "tarde"],
    category: "Electricidad",
    specialty: "Electricista",
    paymentMethods: ["Efectivo", "Mercado Pago"],
    workingArea: ["CABA", "GBA Zona Sur", "GBA Zona Norte"],
    isActive: true,
  },
  {
    typePost: "Offer",
    title: "Cuidado de niños",
    description: "Venenatis phasellus quis vel enim sociosqu congue quam.",
    image: "",
    priceRange: ["500", "1000"],
    timeRange: ["mañana", "tarde", "noche"],
    category: "Cuidado de niños/adolescentes",
    specialty: "Niñera",
    paymentMethods: ["Efectivo"],
    workingArea: ["CABA"],
    isActive: true,
  },
  {
    typePost: "Offer",
    title: "Costurera",
    description: "Venenatis phasellus quis vel enim sociosqu congue quam.",
    image: "",
    priceRange: ["500", "1500"],
    timeRange: ["mañana", "tarde"],
    category: "Costura",
    specialty: "Costurera",
    paymentMethods: ["Efectivo", "Mercado Pago"],
    workingArea: ["CABA"],
    isActive: true,
  },
  {
    typePost: "Offer",
    title: "Carpintero",
    description:
      "Ultrices eleifend dis porttitor auctor condimentum vehicula habitasse, facilisis duis.",
    image: "",
    priceRange: ["700", "1500"],
    timeRange: ["mañana", "tarde"],
    category: "Carpinteria",
    specialty: "Carpintero",
    paymentMethods: ["Mercado Pago"],
    workingArea: ["CABA", "GBA Zona Norte"],
    isActive: true,
  },
  {
    typePost: "Petition",
    title: "Profesor tutor",
    description:
      "sollicitudin magna euismod aenean quisque eu. Ullamcorper tempor habitasse sociis inceptos ultrices ornare integer.",
    image: "",
    priceRange: ["200", "800"],
    timeRange: ["mañana", "tarde"],
    category: "Tutorias",
    specialty: "Profesor",
    paymentMethods: ["Mercado Pago"],
    workingArea: ["CABA"],
    isActive: true,
  },
  {
    typePost: "Offer",
    title: "Zapatero",
    description:
      "habitasse sociis inceptos ultrices ornare integer, nostra a nunc ultricies gravida facilis integer.",
    image: "",
    priceRange: ["200", "1000"],
    timeRange: ["mañana", "tarde"],
    category: "Zapatero",
    specialty: "Zapateror",
    paymentMethods: ["Mercado Pago"],
    workingArea: ["GBA Zona Sur"],
    isActive: false,
  },
  {
    typePost: "Petition",
    title: "Volantero",
    description:
      "habitasse sociis inceptos ultrices ornare integer, nostra a nunc ultricies gravida facilis integer.",
    image: "",
    priceRange: ["200", "800"],
    timeRange: ["mañana", "tarde"],
    category: "Volantero",
    specialty: "Volantero",
    paymentMethods: ["Efectivo", "Mercado Pago"],
    workingArea: ["GBA Zona Norte", "CABA", "GBA Zona Sur"],
    isActive: false,
  },
  {
    typePost: "Offer",
    title: "Gasista",
    description:
      "habitasse sociis inceptos ultrices ornare integer, nostra a nunc ultricies gravida facilis integer.",
    image: "",
    priceRange: ["500", "2500"],
    timeRange: ["mañana", "tarde"],
    category: "Gasista",
    specialty: "Gasista Matriculado",
    paymentMethods: ["Transferencia", "Efectivo", "Mercado Pago"],
    workingArea: ["GBA Zona Sur"],
    isActive: true,
  },
  {
    typePost: "Offer",
    title: "Barrendero",
    description:
      "habitasse sociis inceptos ultrices ornare integer, nostra a nunc ultricies gravida facilis integer.",
    image: "",
    priceRange: ["200", "800"],
    timeRange: ["mañana", "tarde"],
    category: "Limpieza",
    specialty: "Barrendero",
    paymentMethods: ["Mercado Pago"],
    workingArea: ["CABA"],
    isActive: false,
  },
];

module.exports = postsDB;
