const postsDB = [
  {
    user_id: "f7f32520-8568-4749-bc78-195ebc625866",
    typePost: "Offer",
    title: "Se ofrecen servicios de albañileria y relacionados",
    description: "Venenatis phasellus quis vel enim sociosqu congue quam.",
    image: "",
    priceRange: ["500", "1000"],
    timeRange: ["mañana", "tarde"],
    category_id: 101,
    specialty_id: 1000,
    paymentMethods: ["Efectivo", "MercadoPago", "Transferencia", "Crédito", "Débito"],
    workingArea: ["CABA", "GBA Zona Sur"],
    isActive: true,
  },
  {
    user_id: "1e907d14-5b6c-4595-b368-ae0ce9a95fc5",
    typePost: "Offer",
    title: "Electricista a domicilio",
    description: "Venenatis phasellus quis vel enim sociosqu congue quam.",
    image: "",
    priceRange: ["800", "1000"],
    timeRange: ["mañana", "tarde"],
    category_id: 101,
    specialty_id: 1037,
    paymentMethods: ["Efectivo", "Mercado Pago"],
    workingArea: ["CABA", "GBA Zona Sur", "GBA Zona Norte"],
    isActive: true,
  },
  {
    user_id: "575fc767-a451-4e60-853a-f2269e57a9c4",
    typePost: "Offer",
    title: "Cuidado de niños a domicilio / en hogar",
    description: "Venenatis phasellus quis vel enim sociosqu congue quam.",
    image: "",
    priceRange: ["500", "1000"],
    timeRange: ["mañana", "tarde", "noche"],
    category_id: 105,
    specialty_id: 5008,
    paymentMethods: ["Efectivo"],
    workingArea: ["CABA"],
    isActive: true,
  },
  {
    user_id: "29347ce5-d55b-42ab-886e-28df6dd7e725",
    typePost: "Offer",
    title: "Costurera: La mejor de Bernal",
    description: "Venenatis phasellus quis vel enim sociosqu congue quam.",
    image: "",
    priceRange: ["500", "1500"],
    timeRange: ["mañana", "tarde"],
    category_id: 101,
    specialty_id: 1028,
    paymentMethods: ["Efectivo", "Mercado Pago"],
    workingArea: ["CABA"],
    isActive: true,
  },
  {
    user_id: "2b134353-a0d6-4e67-99bb-f65cbe398160",
    typePost: "Offer",
    title: "Carpintero: 50 años de experiencia",
    description: "Ultrices eleifend dis porttitor auctor condimentum vehicula habitasse, facilisis duis.",
    image: "",
    priceRange: ["700", "1500"],
    timeRange: ["mañana", "tarde"],
    category_id: 101,
    specialty_id: 1017,
    paymentMethods: ["Mercado Pago"],
    workingArea: ["CABA", "GBA Zona Norte"],
    isActive: true,
  },
  {
    user_id: "3d55921e-3e03-40de-a2f0-284b809fbf6b",
    typePost: "Petition",
    title: "Profesor de programación. Preparo alumnos para checkpoints de Henry",
    description: "sollicitudin magna euismod aenean quisque eu. Ullamcorper tempor habitasse sociis inceptos ultrices ornare integer.",
    image: "",
    priceRange: ["200", "800"],
    timeRange: ["mañana", "tarde"],
    category_id: 107,
    specialty_id: 7001,
    paymentMethods: ["Mercado Pago"],
    workingArea: ["CABA"],
    isActive: true,
  },
  {
    user_id: "c077a4b3-8c77-4501-9fa7-663509c8ccc2",
    typePost: "Offer",
    title: "Zapatero Zona Sur",
    description: "habitasse sociis inceptos ultrices ornare integer, nostra a nunc ultricies gravida facilis integer.",
    image: "",
    priceRange: ["200", "1000"],
    timeRange: ["mañana", "tarde"],
    category_id: 101,
    specialty_id: 1115,
    paymentMethods: ["Mercado Pago"],
    workingArea: ["GBA Zona Sur"],
    isActive: false,
  },
  {
    user_id: "b15b1116-d9c1-4bed-ad19-99af3456d628",
    typePost: "Petition",
    title: "Volantero para evento social",
    description: "habitasse sociis inceptos ultrices ornare integer, nostra a nunc ultricies gravida facilis integer.",
    image: "",
    priceRange: ["200", "800"],
    timeRange: ["mañana", "tarde"],
    category_id: 101,
    specialty_id: 1113,
    paymentMethods: ["Efectivo", "Mercado Pago"],
    workingArea: ["GBA Zona Norte", "CABA", "GBA Zona Sur"],
    isActive: false,
  },
  {
    user_id: "870cac3c-b251-4962-a7a6-016eb14b8a09",
    typePost: "Offer",
    title: "Gasista matriculado Precios imbatibles",
    description: "habitasse sociis inceptos ultrices ornare integer, nostra a nunc ultricies gravida facilis integer.",
    image: "",
    priceRange: ["500", "2500"],
    timeRange: ["mañana", "tarde"],
    category_id: 101,
    specialty_id: 1116,
    paymentMethods: ["Transferencia", "Efectivo", "Mercado Pago"],
    workingArea: ["GBA Zona Sur"],
    isActive: true,
  },
  {
    user_id: "272ece37-cb57-47c1-86ec-42784cb288a4",
    typePost: "Offer",
    title: "Chofer a domicilio",
    description: "habitasse sociis inceptos ultrices ornare integer, nostra a nunc ultricies gravida facilis integer.",
    image: "",
    priceRange: ["200", "800"],
    timeRange: ["mañana", "tarde"],
    category_id: 103,
    specialty_id: 3001,
    paymentMethods: ["Mercado Pago"],
    workingArea: ["CABA"],
    isActive: false,
  },
];

module.exports = postsDB;
