const usersDB = [
      {
        firstname: "Jhon",
        lastname: "Doe",
        age: 29,
        ID_Passport: '12345678',
        address: "Calle Campana 235, Palermo",
        phoneNumber: 1135698745,
        email: "user01@changas.com",
        summary: 'Venenatis phasellus quis vel enim sociosqu congue quam.',
        photo: "",
        score: 4.5,
        jobDone: 2,
        isVaccinated: true,
        isNew: false,
        isAdmin: false,
        isActive: true,
      },
      {
        firstname: "Susana",
        lastname: "Farris",
        age: 32,
        ID_Passport: '45678965',
        address: "Calle Rioja 565, Parque Chacabuco",
        phoneNumber: 113548795,
        email: "user02@changas.com",
        summary: 'Venenatis phasellus quis vel enim sociosqu congue quam.',
        photo: "",
        score: 3.5,
        jobDone: 0,
        isVaccinated: true,
        isNew: true,
        isAdmin: false,
        isActive: true,
      },
      {
        firstname: "Pedro",
        lastname: "Perez",
        age: 45,
        ID_Passport: '45678965',
        address: "Calle Valentin 565, Flores",
        phoneNumber: 113548795,
        email: "user03@changas.com",
        summary: 'Venenatis phasellus quis vel enim sociosqu congue quam.',
        photo: "",
        score: 5,
        jobDone: 10,
        isVaccinated: false,
        isNew: false,
        isAdmin: false,
        isActive: false,
      },
      {
        firstname: "Ines",
        lastname: "Coronado",
        age: 21,
        ID_Passport: '45678965',
        address: "Calle Barraca 55, Moreno",
        phoneNumber: 113548795,
        email: "user04@changas.com",
        summary: 'Venenatis phasellus quis vel enim sociosqu congue quam.',
        photo: "",
        score: 1,
        jobDone: 2,
        isVaccinated: true,
        isNew: false,
        isAdmin: false,
        isActive: true,
      },
      {
        firstname: "Rosa",
        lastname: "Perez",
        age: 56,
        ID_Passport: '97027491',
        address: "Padilla 827, Quilmes, GBA Zona Sur",
        phoneNumber: 11356918365,
        email: "rosa_user02@changas.com",
        summary: 'Venenatis phasellus quis vel enim sociosqu congue quam.',
        photo: "",
        score: 5,
        jobDone: 3,
        isVaccinated: true,
        isNew: false,
        isAdmin: false,
        isActive: true,
      },
      {
        firstname: "Jorge",
        lastname: "Vega",
        age: 40,
        ID_Passport: '455JK08',
        address: "Castro 298, Chacarita",
        phoneNumber: 1156904951,
        email: "jorgevegauser@changas.com",
        summary: 'Venenatis phasellus quis vel enim sociosqu congue quam.',
        photo: "",
        score: 4.0,
        jobDone: 5,
        isVaccinated: true,
        isNew: false,
        isAdmin: false,
        isActive: true,
      },
      {
        firstname: "Cacho",
        lastname: "Castaña",
        age: 18,
        ID_Passport: '12345678',
        address: "Calamuchita 24, Esq. Croto",
        phoneNumber: 1135698745,
        email: "user01@changas.com",
        summary: "Lorem ipsum, Lorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsum",
        photo: "",
        score: 4,
        jobDone: 2,
        isVaccinated: false,
        isNew: true,
        isAdmin: false,
        isActive: true,
      },
      {
        firstname: "Bart",
        lastname: "Simpson",
        age: 23,
        ID_Passport: '12345678',
        address: "Avenida SiempreViva, Springfield",
        phoneNumber: 1135698745,
        email: "user01@changas.com",
        summary: "Lorem ipsum, Lorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsum",
        photo: "",
        score: 5,
        jobDone: 0,
        isVaccinated: false,
        isNew: true,
        isAdmin: false,
        isActive: true,
      },
      {
        firstname: "Juan Roman",
        lastname: "Riquelme",
        age: 65,
        ID_Passport: '12345678',
        address: "Hipolito Yrigoyen 2000, Ciudad Oculta",
        phoneNumber: 1135698745,
        email: "user01@changas.com",
        summary: "Lorem ipsum, Lorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsum",
        photo: "",
        score: 2.5,
        jobDone: 25,
        isVaccinated: true,
        isNew: true,
        isAdmin: false,
      },
      {
        firstname: "Laura",
        lastname: "Fernandez",
        age: 37,
        ID_Passport: '43215678',
        address: "Chacabuco 705, CABA",
        phoneNumber: 11356989276,
        email: "user_laura@changas.com",
        summary: 'Venenatis phasellus quis vel enim sociosqu congue quam.',
        photo: "",
        score: 3,
        jobDone: 1,
        isVaccinated: false,
        isNew: false,
        isAdmin: false,
        isActive: true,
      },
    ]

module.exports = usersDB;