const usersDB = [
  {
    firstName: "Jhon",
    lastName: "Doe",
    age: 29,
    ID_Passport: '14141414',
    address: "Calle Campana 235, Palermo",
    phoneNumber: 1135698745,
    email: "user_fulanito@changas.com",
    summary: 'Venenatis phasellus quis vel enim sociosqu congue quam.',
    photo: "",
    score: 4.5,
    jobDone: 2,
    isVaccinated: true,
    isNew: false,
    isAdmin: false,
    isActive: true,
  },
  {
    firstName: "Susana",
    lastName: "Farris",
    age: 32,
    ID_Passport: '25252525',
    address: "Calle Rioja 565, Parque Chacabuco",
    phoneNumber: 113548795,
    email: "user_susana@changas.com",
    summary: 'Venenatis phasellus quis vel enim sociosqu congue quam.',
    photo: "",
    score: 3.5,
    jobDone: 0,
    isVaccinated: true,
    isNew: true,
    isAdmin: false,
    isActive: true,
  },
  {
    firstName: "Pedro",
    lastName: "Perez",
    age: 45,
    ID_Passport: '52468549',
    address: "Calle Valentin 565, Flores",
    phoneNumber: 113548795,
    email: "user_pedro@changas.com",
    summary: 'Venenatis phasellus quis vel enim sociosqu congue quam.',
    photo: "",
    score: 5,
    jobDone: 10,
    isVaccinated: false,
    isNew: false,
    isAdmin: false,
    isActive: false,
  },
  {
    firstName: "Ines",
    lastName: "Coronado",
    age: 21,
    ID_Passport: '36363636',
    address: "Calle Barraca 55, Moreno",
    phoneNumber: 113548795,
    email: "user_ines@changas.com",
    summary: 'Venenatis phasellus quis vel enim sociosqu congue quam.',
    photo: "",
    score: 1,
    jobDone: 2,
    isVaccinated: true,
    isNew: false,
    isAdmin: false,
    isActive: true,
  },
  {
    firstName: "Rosa",
    lastName: "Perez",
    age: 56,
    ID_Passport: '47474747',
    address: "Padilla 827, Quilmes, GBA Zona Sur",
    phoneNumber: 11356918365,
    email: "rosa_user02@changas.com",
    summary: 'Venenatis phasellus quis vel enim sociosqu congue quam.',
    photo: "",
    score: 5,
    jobDone: 3,
    isVaccinated: true,
    isNew: false,
    isAdmin: false,
    isActive: true,
  },
  {
    firstName: "Jorge",
    lastName: "Vega",
    age: 40,
    ID_Passport: '58585858',
    address: "Castro 298, Chacarita",
    phoneNumber: 1156904951,
    email: "jorgevegauser@changas.com",
    summary: 'Venenatis phasellus quis vel enim sociosqu congue quam.',
    photo: "",
    score: 4.0,
    jobDone: 5,
    isVaccinated: true,
    isNew: false,
    isAdmin: false,
    isActive: true,
  },
  {
    firstName: "Cacho",
    lastName: "Castaña",
    age: 18,
    ID_Passport: '69696969',
    address: "Calamuchita 24, Esq. Croto",
    phoneNumber: 1135698745,
    email: "polemicaenelbar@changas.com",
    summary: "Lorem ipsum, Lorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsum",
    photo: "",
    score: 4,
    jobDone: 2,
    isVaccinated: false,
    isNew: true,
    isAdmin: false,
    isActive: true,
  },
  {
    firstName: "Bart",
    lastName: "Simpson",
    age: 23,
    ID_Passport: '12121212',
    address: "Avenida SiempreViva, Springfield",
    phoneNumber: 1135698745,
    email: "elbarto@changas.com",
    summary: "Lorem ipsum, Lorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsum",
    photo: "",
    score: 5,
    jobDone: 0,
    isVaccinated: false,
    isNew: true,
    isAdmin: false,
    isActive: true,
  },
  {
    firstName: "Juan Roman",
    lastName: "Riquelme",
    age: 65,
    ID_Passport: '23232323',
    address: "Hipolito Yrigoyen 2000, Ciudad Oculta",
    phoneNumber: 1135698745,
    email: "user_juanroman@changas.com",
    summary: "Lorem ipsum, Lorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsum",
    photo: "",
    score: 2.5,
    jobDone: 25,
    isVaccinated: true,
    isNew: true,
    isAdmin: false,
    isActive: true,
  },
  {
    firstName: "Laura",
    lastName: "Fernandez",
    age: 37,
    ID_Passport: '45454545',
    address: "Chacabuco 705, CABA",
    phoneNumber: 11356989276,
    email: "user_laura@changas.com",
    summary: 'Venenatis phasellus quis vel enim sociosqu congue quam.',
    photo: "",
    score: 3,
    jobDone: 1,
    isVaccinated: false,
    isNew: false,
    isAdmin: false,
    isActive: true,
  },
]

module.exports = usersDB;